<?php if($page != 3){ ?>
    
<!-- NO PANEL -->
<link rel="stylesheet" type="text/css" media="screen" href="css/normalize.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/base.css">

<?php } ?>




<!-- PAR PAGE -->
<?php if($page == 1 || $page == 2){ ?>
    
<link rel="stylesheet" type="text/css" media="screen" href="css/index.css">

<?php } ?>

<link rel='stylesheet' href='https://unpkg.com/css-pro-layout@1.1.0/dist/css/css-pro-layout.css'>
<link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/remixicon@2.2.0/fonts/remixicon.css'>

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet"> 

<link rel="stylesheet" href="css/sidebar.css">

<!-- ALL -->
<link rel="stylesheet" type="text/css" media="screen" href="css/all.css">



