
        <?php
/*
        if($page == 1){
            echo "Accuiel";
        } else if($page ==2){
            echo "Connection";
        } else{


            echo "NULL";
        }

*/


        ?>
        <div class="container text-white py-4">
            <nav class="d-flex align-items-center justify-content-between">
                <a id="logo" href="#"><img src="assets/logo.png" alt="logo useritium"></a>
                <ul class="d-flex">
                    <li class="ms-4"><a href="index.php">Accueil</a></li>
                    <li class="ms-4"><a href="connect.php">Connect</a></li>
                    <li class="ms-4"><a href="home.php">Panel</a></li>
                </ul>
            </nav>
            <h1 class="text-center display-1">Compte Useritium</h1>
        </div>