<?php

    if($page == 1){

?>
      
    <div class="container text-white py-4">
        <nav class="d-flex align-items-center justify-content-between">
            <a id="logo" href="#"><img src="assets/logo.png" alt="logo useritium"></a>
            <ul class="d-flex">
                <li class="ms-4"><a href="index.php">Accueil</a></li>
                <?php if(!$isLogged){ ?>
                <li class="ms-4"><a href="connect.php" class="btn-super">Connexion / Inscription</a></li>
                <?php } else { ?>
                <li class="ms-4"><a href="home.php" class="btn-super">Panel</a></li>
                <li class="ms-4"><a style="text-decoration: underline;" href="?modeDeco=on">Déconnexion</a></li>
                <?php } ?>
            </ul>
        </nav>
        <h1 class="text-center display-1">Compte Useritium
            <br>
            <a class="btn btn-light" style="color: black; font-size: 14px;" href="connect.php">Connexion / Inscription</a></h1>
    </div>


<?php

    } else if($page ==2){

?>
      <nav class="d-flex align-items-center justify-content-between">
            <a id="logo" href="." style="font-size: 25px;"><img src="assets/logo.png" alt="logo useritium"> Compte Useritium </a>
            <ul class="d-flex">
                <li class="ms-4"><a href="index.php">Accueil</a></li>
                <?php if(!$isLogged){ ?>
                <li class="ms-4"><a href="connect.php" class="btn-super">Connexion / Inscription</a></li>
                <?php } else { ?>
                <li class="ms-4"><a href="home.php" class="btn-super">Panel</a></li>
                <li class="ms-4"><a style="text-decoration: underline;" href="?modeDeco=on">Déconnexion</a></li>
                <?php } ?>
            </ul>
        </nav>
        
<?php

    } else {

        echo "NULL";

    }

?>
        