<?php

    if($page == 1 ){

?>
      
    <div class="container text-white py-4">
        <nav class="d-flex align-items-center justify-content-between">
            <a id="logo" href="#"><img src="assets/logo.png" alt="logo useritium"></a>
            <ul class="d-flex">
                <li class="ms-4"><a href="index.php">Accueil</a></li>
                <li class="ms-4"><a href="https://dashboard.useritium.fr" class="btn-super">Connexion / Inscription</a></li>
            </ul>
        </nav>
        <h1 class="text-center display-1 bold" style="text-shadow: 1px 1px 2px black;">Compte Useritium<br>
            <a class="btn btn-light" style="color: black; font-size: 14px;" href="https://dashboard.useritium.fr">Connexion / Inscription</a></h1>
    </div>
<?php

    } else if ($page == 999999) {

        ?>

        <div class="container text-white py-4">
            <nav class="d-flex align-items-center justify-content-between">
                <a id="logo" href="#"><img src="assets/logo.png" alt="logo useritium"></a>
                <ul class="d-flex" style="margin: unset;">
                    <li class="ms-4"><a href="index.php">Accueil</a></li>
                        <li class="ms-4"><a href="https://dashboard.useritium.fr" class="btn-super">Connexion / Inscription</a></li>
                </ul>
            </nav>
        </div>


        <?php

    } else {

        echo "NULL";

    }

?>
        