<div class="layout has-sidebar fixed-sidebar fixed-header">
    <aside id="sidebar" class="sidebar break-point-lg has-bg-image">
        <div class="image-wrapper">
            <img src="https://user-images.githubusercontent.com/25878302/144499035-2911184c-76d3-4611-86e7-bc4e8ff84ff5.jpg" alt="sidebar background" />
        </div>
        <div class="sidebar-layout">
            <div class="sidebar-header">
        <span style="
                text-transform: uppercase;
                font-size: 15px;
                letter-spacing: 3px;
                font-weight: bold;
              "><a href=".">Useritium
<span class="badge badge-info">Bêta</span></a></span>
            </div>
            <div class="sidebar-content">
                <nav class="menu open-current-submenu">
                    <ul>
                    <li class="menu-item">
                            <a href="?p=1">
                                <span class="menu-icon"><i class="ri-home-line"></i>
                                </span>
                                <span class="menu-title">Accueil</span>

                            </a>
                        </li>
                        <!-- <li class="menu-item sub-menu">
                            <a href="#">
                            <span class="menu-icon"><i class="ri-shield-user-line"></i>
                            </span>
                                <span class="menu-title">Compte</span>
                            </a>
                            <div class="sub-menu-list">
                                <ul>
                                    <li class="menu-item">
                                        <a href="?p=20">
                                            <span class="menu-title">Grid</span>
                                        </a>
                                    </li>
                                    <li class="menu-item">
                                        <a href="?p=21">
                                            <span class="menu-title">Layout</span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </li> -->
                        <li class="menu-item">
                            <a href="?p=2">
                                <span class="menu-icon"><i class="ri-shield-user-line"></i>
                                </span>
                                <span class="menu-title">Compte</span>

                            </a>
                        </li>
                        <li class="menu-item">
                            <a href="?p=3">
                                <span class="menu-icon"><i class="ri-mail-line"></i>
                                </span>
                                <span class="menu-title">Messagerie</span>

                            </a>
                        </li>
                        <li class="menu-item">
                            <a href="?p=4">
                                <span class="menu-icon"><i class="ri-sticky-note-line"></i>
                                </span>
                                <span class="menu-title">Notes</span>

                            </a>
                        </li>
                        <li class="menu-item">
                            <a href="?p=5">
                                <span class="menu-icon"><i class="ri-file-line"></i>
                                </span>
                                <span class="menu-title">Documents</span>

                            </a>
                        </li>
                        <li class="menu-item">
                            <a href="?p=6">
                                <span class="menu-icon"><i class="ri-cloudy-line"></i>
                                </span>
                                <span class="menu-title">Cloud</span>

                            </a>
                        </li>
                        <li class="menu-item">
                            <a href="?p=7">
                                <span class="menu-icon"><i class="ri-price-tag-3-line"></i>
                                </span>
                                <span class="menu-title">Prestations</span>

                            </a>
                        </li>
                        <li class="menu-item">
                            <a href="?p=8">
                                <span class="menu-icon"><i class="ri-gamepad-line"></i>
                                </span>
                                <span class="menu-title">Jeux</span>

                            </a>
                        </li>
                        <li class="menu-item">
                            <a href="?p=9">
                                <span class="menu-icon"><i class="ri-server-line"></i>
                                </span>
                                <span class="menu-title">Serveurs</span>

                            </a>
                        </li>
                        <li class="menu-item">
                            <a href="?modeDeco=on">
                                <span class="menu-icon">
                                    <i class="ri-logout-box-r-line"></i>
                                </span>
                                <span class="menu-title">Déconnexion</span>

                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
            <div class="sidebar-footer"><span>2022 © <a target="_blank" href="https://tyrolium.fr">TYROLIUM</a></span></div>
        </div>
    </aside>
    <div id="overlay" class="overlay"></div>
    <div class="layout">
        <header class="header">
            <a id="btn-collapse" href="#">
                <i class="ri-menu-line ri-xl"></i>
            </a>
            <a id="btn-toggle" href="#" class="sidebar-toggler break-point-lg">
                <i class="ri-menu-line ri-xl"></i>
            </a>
        </header>

