<div class="layout has-sidebar fixed-sidebar fixed-header">
    <aside id="sidebar" class="sidebar break-point-lg has-bg-image">
        <div class="image-wrapper">
            <img src="https://user-images.githubusercontent.com/25878302/144499035-2911184c-76d3-4611-86e7-bc4e8ff84ff5.jpg" alt="sidebar background" />
        </div>
        <div class="sidebar-layout">
            <div class="sidebar-header">
        <span style="
                text-transform: uppercase;
                font-size: 15px;
                letter-spacing: 3px;
                font-weight: bold;
              ">


            <?php if(empty($_COOKIE['DesktopApp'])){?>

                <a href=".">Useritium
                    <span class="badge badge-info">Bêta</span>
                </a>

            <?php } else { ?>

                <a href="./panel.php">Useritium
                    <span class="badge badge-light">Bêta App</span>
                </a>

            <?php } ?>


        </span>
            </div>
            <div class="sidebar-content">
                <nav class="menu open-current-submenu">
                    <ul>
                    <li class="menu-item">
                            <a href="?p=1">
                                <span class="menu-icon"><i class="ri-home-line"></i>
                                </span>
                                <span class="menu-title">Accueil</span>

                            </a>
                        </li>
                        <li class="menu-item">
                            <a href="?p=2">
                                <span class="menu-icon"><i class="ri-shield-user-line"></i>
                                </span>
                                <span class="menu-title">Compte</span>

                            </a>
                        </li>
                        <li class="menu-item">
                            <a href="?p=3">
                                <span class="menu-icon"><i class="ri-mail-line"></i>
                                </span>
                                <span class="menu-title">Messagerie</span>

                            </a>
                        </li>
                        <li class="menu-item">
                            <a href="?p=4">
                                <span class="menu-icon"><i class="ri-sticky-note-line"></i>
                                </span>
                                <span class="menu-title">Notes</span>

                            </a>
                        </li>
                        <li class="menu-item">
                            <a href="?p=5">
                                <span class="menu-icon"><i class="ri-file-line"></i>
                                </span>
                                <span class="menu-title">Documents</span>

                            </a>
                        </li>
                        <li class="menu-item">
                            <a href="?p=6">
                                <span class="menu-icon"><i class="ri-cloudy-line"></i>
                                </span>
                                <span class="menu-title">Cloud</span>

                            </a>
                        </li>
                        <li class="menu-item">
                            <a href="?p=7">
                                <span class="menu-icon"><i class="ri-price-tag-3-line"></i>
                                </span>
                                <span class="menu-title">Prestations</span>

                            </a>
                        </li>
                        <li class="menu-item">
                            <a href="?p=8">
                                <span class="menu-icon"><i class="ri-gamepad-line"></i>
                                </span>
                                <span class="menu-title">Jeux</span>

                            </a>
                        </li>
                        <li class="menu-item">
                            <a href="?p=9">
                                <span class="menu-icon"><i class="ri-server-line"></i>
                                </span>
                                <span class="menu-title">Serveurs</span>

                            </a>
                        </li>
                        <li class="menu-item">
                            <a href="?modeDeco=on">
                                <span class="menu-icon">
                                    <i class="ri-logout-box-r-line"></i>
                                </span>
                                <span class="menu-title">Déconnexion</span>

                            </a>
                        </li>
                        <hr style="background: #b3b8d4;margin: 7px 37px;">
                        <li class="menu-item">
                            <a href="?p=10">
                                <span class="menu-icon"><img class="icon-sidebar" src="https://tyrolium.fr/Contenu/Image/Tyrolium%20ServerMC%20Sword%203D.png">
                                </span>
                                <span class="menu-title">TyroServ</span>

                            </a>
                        </li>
                        <li class="menu-item">
                            <a href="?p=11">
                                <span class="menu-icon"><img class="icon-sidebar" src="https://tyrolium.fr/Contenu/Image/Gamenium%20Site.png">
                                </span>
                                <span class="menu-title">Gamenium</span>

                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
            <div class="sidebar-footer"><span>2024 © <a target="_blank" href="https://tyrolium.fr">TYROLIUM</a></span></div>
        </div>
    </aside>
    <div id="overlay" class="overlay"></div>
    <div class="layout">
        <header class="header">
            <a id="btn-collapse" href="#">
                <i class="ri-menu-line ri-xl"></i>
            </a>
            <a id="btn-toggle" href="#" class="sidebar-toggler break-point-lg">
                <i class="ri-menu-line ri-xl"></i>
            </a>
        </header>

