<div class="layout has-sidebar fixed-sidebar fixed-header">
    <aside id="sidebar" class="sidebar break-point-lg has-bg-image">
        <div class="image-wrapper">
            <img src="https://user-images.githubusercontent.com/25878302/144499035-2911184c-76d3-4611-86e7-bc4e8ff84ff5.jpg" alt="sidebar background" />
        </div>
        <div class="sidebar-layout">
            <div class="sidebar-header">
        <span style="
                text-transform: uppercase;
                font-size: 15px;
                letter-spacing: 3px;
                font-weight: bold;
              ">TyroMail</span>
            </div>
            <div class="sidebar-content">
                <nav class="menu open-current-submenu">
                    <ul>
                        <li class="menu-item sub-menu">
                            <a href="#">
                            <span class="menu-icon">
                              <i class="ri-vip-diamond-fill"></i>
                            </span>
                                <span class="menu-title">Accounts</span>
                                <span class="menu-suffix">&#x1F525;</span>
                            </a>
                            <div class="sub-menu-list">
                                <ul>
                                    <li class="menu-item">
                                        <a href="#">
                                            <span class="menu-title">Grid</span>
                                        </a>
                                    </li>
                                    <li class="menu-item">
                                        <a href="#">
                                            <span class="menu-title">Layout</span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                        <li class="menu-item">
                            <a href="?modeDeco=on">
                                <span class="menu-icon">
                                    <i class="ri-logout-box-r-line"></i>
                                </span>
                                <span class="menu-title">Déconnexion</span>

                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
            <div class="sidebar-footer"><span>Sidebar footer</span></div>
        </div>
    </aside>
    <div id="overlay" class="overlay"></div>
    <div class="layout">
        <header class="header">
            <a id="btn-collapse" href="#">
                <i class="ri-menu-line ri-xl"></i>
            </a>
            <a id="btn-toggle" href="#" class="sidebar-toggler break-point-lg">
                <i class="ri-menu-line ri-xl"></i>
            </a>
        </header>

