<section id="panel-account">

    <h3 class="title-morph">Profile Publique</h3>
    <div class="card-morph">
        <form method="POST" enctype="multipart/form-data">
            <?php
            require "app/env.php";
            $premiereLettreName = substr($_SESSION['userNameLog'], 0, 1);
            ?>
            <div id="prePP">
                <?php if (!$_SESSION["userPpLog"]){ ?>
                    <div id="PP" style="background-image: url('https://tyrolium.fr/generate-pp/?c=183153&l=<?= $premiereLettreName ?>')"></div>
                <?php } else { ?>
                    <div id="PP" style="background-image: url('<?= $env_uploadUrl . "pp/" . $_SESSION["userPpLog"] ?>')"></div>
                <?php } ?>
            </div>

            <div class="form-group">
                <label>Votre Image (9 Mo Max)</label>
                <input type="file" class="form-control input-morph" name="pictureProfilAdd">
            </div>

            <input type="hidden" name="idEdit" value="<?= $_SESSION['userIdLog'] ?>">
            <br>
            <button type="submit" class="btn btn-primary" style="width: 100%">Envoyer</button>

        </form>

        <form method="POST">
            <div class="form-group">
                <h4><?= $_SESSION['userNameLog'] ?></h4>
            </div>
            <div class="form-group">
                <label>Nom d'affichage</label>
                <input type="text" class="input-morph" name="displayEdit" placeholder="Pierre Jean Dupond" value="<?php if(!empty($_SESSION['userDisNameLog']) ) { echo $_SESSION['userDisNameLog']; } ?>">
            </div>
            <div class="form-group">
                <label>Adresse Email</label>
                <input type="text" class="input-morph" name="emailEdit" placeholder="name@example.com" value="<?= $_SESSION['userEmailLog'] ?>">
            </div>
            <!-- <div class="form-group">
                <label for="exampleFormControlTextarea1">Bio</label>
                <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"><?php if(!empty($_SESSION['userBioLog']) ) { echo $_SESSION['userBioLog']; } ?></textarea>
            </div> -->

            <input type="hidden" name="idEdit" value="<?= $_SESSION['userIdLog'] ?>">
            <br>
            <button type="submit" class="btn btn-primary" style="width: 100%">Envoyer</button>

        </form>
    </div>
    <br><br>

    <hr>

    <br><br>

    <h3  class="title-morph">Vérification des emails</h3>
    <div class="card-morph">


    </div>



    <br><br>

    <hr>

    <br><br>

    <h3  class="title-morph">Mots de passe</h3>
    <form method="POST" class="card-morph">
        <div class="form-group">
            <label>Ancien Mots de passe</label>
            <input type="password" name="passEditNewOld" class="input-morph" placeholder="">
        </div>
        <div class="form-group">
            <label>Nouveau Mots de passe</label>
            <input type="password" name="passEditNew" class="input-morph" placeholder="">
        </div>
        <div class="form-group">
            <label>Comfirmer le Nouveau Mots de passe</label>
            <input type="password" name="passEditNewC" class="input-morph" placeholder="">
        </div>
        <br>
        <input type="hidden" name="idEditPass" value="<?= $_SESSION['userIdLog'] ?>">
        <button type="submit" class="btn btn-primary" style="width: 100%">Envoyer</button>
    </form>

    <br><br>

    <hr>

    <br><br>

    <h3  class="title-morph">Compte Liée</h3>
    <div class="card-morph">


    </div>



    <br><br>

</section>

<style>
    #PP {
        width: 200px;
        height: 200px;
        box-shadow: 0px 4px 83px rgba(0, 0, 0, 0.24);
        border-radius: 133px;
        background-size: contain;
        background-color: white;
        background-repeat: no-repeat;
        margin: auto;
    }

        #prePP{
            width: 100%;
        }


</style>
