<section id="panel-account">

    <h3 class="title-morph">Profile Publique</h3>
    <div class="card-morph">
        <form method="POST" enctype="multipart/form-data">
            <?php
            require "app/env.php";
            $premiereLettreName = substr($_SESSION['userNameLog'], 0, 1);
            ?>

            <div id="PPnoChange" style="display: block;height: 227px;">
                <div id="prePP">
                    <?php if (!$_SESSION["userPpLog"]){ ?>
                        <div id="PP" style="background-image: url('https://tyrolium.fr/generate-pp/?c=183153&l=<?= $premiereLettreName ?>')"></div>
                    <?php } else { ?>
                        <div id="PP" style="background-image: url('<?= $env_uploadUrl . "pp/" . $_SESSION["userPpLog"] ?>')"></div>
                    <?php } ?>
                </div>

                <input type="file" class="input-pp pp-morph" name="pictureProfilAdd" onchange="previewImage(event)" onmouseover="hoverPP()" onmouseout="nohoverPP()">
                <div id="uploadIcone">
                    <i class="ri-upload-2-line"></i>
                </div>
            </div>
            <div id="PPchange" style="display: none;">
                <div style="display: flex">
                    <div id="prePP">
                        <?php if (!$_SESSION["userPpLog"]){ ?>
                            <div id="PP" class="pp-morph" style="background-image: url('https://tyrolium.fr/generate-pp/?c=183153&l=<?= $premiereLettreName ?>')"></div>
                        <?php } else { ?>
                            <div id="PP" class="pp-morph" style="background-image: url('<?= $env_uploadUrl . "pp/" . $_SESSION["userPpLog"] ?>')"></div>
                        <?php } ?>
                    </div>

                    <i class="ri-arrow-right-line" style="font-size: 35px;margin-top: 74px;"></i>

                    <div id="prePP">
                        <div id="previewImg" class="ppclass pp-morph"></div>
                    </div>
                </div>
                <br>
                <input type="hidden" name="idEdit" value="<?= $_SESSION['userIdLog'] ?>">

                <div style="margin-bottom: 30px">
                    <div style="width: 80%; margin: auto">
                        <button type="submit" class="btn btn-morph" style="color: #0c92ff;height: 53px;width: 64%;font-size: 14px; margin-right: 19px;"><i class="icon ri-upload-2-line"></i> Appliqué</button>
                        <div onclick="location.reload();" class="btn btn-morph" style="color: #b70707;height: 53px;width: 30%;font-size: 14px;"><i class="icon ri-delete-bin-line"></i> Reset</div>
                    </div>
                </div>
            </div>

            <script src="javascript/photoprofil.js"></script>
        </form>

        <form method="POST">
            <div class="form-group">
                <h4 style="margin-bottom: 30px; text-align: center"><?= $_SESSION['userNameLog'] ?></h4>
            </div>
            <div class="form-group">
                <label>Nom d'affichage</label>
                <input type="text" class="input-morph" name="displayEdit" placeholder="Pierre Jean Dupond" value="<?php if(!empty($_SESSION['userDisNameLog']) ) { echo $_SESSION['userDisNameLog']; } ?>">
            </div>
            <div class="form-group">
                <label>Adresse Email</label>
                <input type="text" class="input-morph" name="emailEdit" placeholder="name@example.com" value="<?= $_SESSION['userEmailLog'] ?>">
            </div>
            <!-- <div class="form-group">
                <label for="exampleFormControlTextarea1">Bio</label>
                <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"><?php if(!empty($_SESSION['userBioLog']) ) { echo $_SESSION['userBioLog']; } ?></textarea>
            </div> -->

            <input type="hidden" name="idEdit" value="<?= $_SESSION['userIdLog'] ?>">
            <br>
            <button type="submit" class="btn btn-morph btn-morph-primary"><i class="icon ri-check-line"></i> Mettre à jour</button>

        </form>
    </div>

    <br><br>
    <hr>
    <br><br>

    <h3  class="title-morph">Vérification des emails</h3>
    <div class="card-morph">

        <!--VERIF MAIL-->

    </div>

    <br><br>
    <hr>
    <br><br>

    <h3  class="title-morph">Mots de passe</h3>
    <form method="POST" class="card-morph">
        <div class="form-group">
            <label>Ancien Mots de passe</label>
            <input type="password" name="passEditNewOld" class="input-morph" placeholder="">
        </div>
        <div class="form-group">
            <label>Nouveau Mots de passe</label>
            <input type="password" name="passEditNew" class="input-morph" placeholder="">
        </div>
        <div class="form-group">
            <label>Comfirmer le Nouveau Mots de passe</label>
            <input type="password" name="passEditNewC" class="input-morph" placeholder="">
        </div>
        <br>
        <input type="hidden" name="idEditPass" value="<?= $_SESSION['userIdLog'] ?>">
        <button type="submit" class="btn btn-morph btn-morph-primary"><i class="icon ri-check-line"></i> Mettre à jour</button>
    </form>

    <br><br>

    <hr>

    <br><br>

    <h3  class="title-morph">Compte Liée</h3>
    <div class="card-morph">

        <!-- COMPTE LIER -->

    </div>

    <br><br>

</section>

<style>

    @media (max-width: 992px) {
        .layout .content {
            padding: 19px 10px;
        }
    }

</style>
