 
<div id="page-wrapper" class="card-morph">
    <h1 class="title-morph">Indisponible pour le moment</h1>
    <div>
        <p>Les comptes Useritium sont encore qu'en bêta, tous les services annoncer lors de sa communication ne sont pas encore fini d'être développé ou d'être testé.<br> Nous vous invitons à nous suivre sur nos réseaux sociaux affins d'être prévenus des futurs sortis</p>
        <br>
        <a class="btn btn-morph btn-morph-primary" style="width:100%" href="https://tyrolium.fr">Site Officiel de Tyrolium</a>
    </div>
</div>

<style>

    #page-wrapper {
        max-width: 600px;
    }

</style>