 
 <div id="page-wrapper">

		<h1>Indisponible pour le moment</h1>
		<div>
      <p>Les comptes Useritium sont encore qu'en bêta, tous les services annoncer lors de sa communication ne sont pas encore fini d'être développé ou d'être testé.<br> Nous vous invitons à nous suivre sur nos réseaux sociaux affins d'être prévenus des futurs sortis</p>
      <br>
      <a class="btn btn-primary" style="width:100%" href="https://tyrolium.fr">Site Officiel de Tyrolium</a>
    </div>

	</div>

    <style>
main.content {
  font-family: Helvetica, Arial, sans-serif;
  font-size: 100%;
  background: #8a94a4 !important;
}

.layout{

    background: #8a94a4 !important;
}

#page-wrapper {
  width: 600px;
  background: #FFF;
  padding: 1em;
  margin: 1em auto;
  min-height: 300px;
  border-top: 5px solid #3a5ff0;
  box-shadow: 0 2px 10px #3a5ff0;
}

h1 {
	margin-top: 0;
}

img {
  max-width: 100%;
}

#fileDisplayArea {
  margin-top: 2em;
  width: 100%;
  overflow-x: auto;
}

@media (max-width: 700px) {
  #page-wrapper {
  width: unset;
  }
}
</style>