<section id="panel-gamenium">

    <h2 class="title-morph">Profil Gamenium</h2>


    <?php

    try {
        $url = 'https://localhost:8000/useritium/' . $_SESSION['userIdLog']; /* CONNECTION A GAMENIUM */

        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
        $output = curl_exec($ch);

        if (curl_errno($ch)) {
            $resultGameniumAPI = (object)['message' => 'error'];
        }

        curl_close($ch);

        $resultGameniumAPI = json_decode($output);

        if (json_last_error() !== JSON_ERROR_NONE) {
            $resultGameniumAPI = (object)['message' => 'error'];
        }
    } catch (Exception $e) {
        $resultGameniumAPI = (object)['message' => 'error'];
    }

    ?>



    <?php if ($resultGameniumAPI->message == "good"){ ?>

        <div class="card-morph">
            <h4><?= $resultGameniumAPI->result ?></h4>
        </div>


    <?php } else { ?>

        <div class="card-morph">
            <h4>Bientôt disponible</h4>
        </div>


    <?php } ?>

</section>
