<section id="panel-game">
    <h3>Vos jeux</h3>
    <br>
    <div class="row">

        <div class="col-12 col-sm-6 col-md-4 col-lg-3">
            <div class="game-back">
                <div class="picture">
                    <img class="img-fluid" src="assets/icone/add.png">
                </div>
                
                <div class="team-content">
                    <h3 class="name">Plus de jeux</h3>
                </div>
            </div>
        </div>
        <div class="col-12 col-sm-6 col-md-4 col-lg-3"  onclick="redirectPanel('https://www.tyroserv.fr/')">
            <div class="game-back">
                <div class="picture">
                    <img class="img-fluid" src="https://tyrolium.fr/Contenu/Image/Tyrolium%20ServerMC%20Sword%203D.png">
                </div>
                
                <div class="team-content">
                    <h3 class="name">TyroServ</h3>
                    <h4 class="title">By TyroServ</h4>
                </div>
            </div>
        </div>

        <div class="col-12 col-sm-6 col-md-4 col-lg-3" onclick="redirectPanel('https://themaxium69.github.io/Flappium/')">
            <div class="game-back">
                <div class="picture">
                    <img class="img-fluid" src="assets/game/flappium.png">
                </div>
                
                <div class="team-content">
                    <h3 class="name">Flappium</h3>
                    <h4 class="title">By Tyrolium</h4>
                </div>
            </div>
        </div>

        <div class="col-12 col-sm-6 col-md-4 col-lg-3" onclick="redirectPanel('https://themaxium69.github.io/Echec-ium/')">
            <div class="game-back">
                <div class="picture">
                    <img class="img-fluid" src="assets/game/Echec-ium.png">
                </div>
                
                <div class="team-content">
                    <h3 class="name">Echec-ium</h3>
                    <h4 class="title">By Tyrolium</h4>
                </div>
            </div>
        </div>

    </div>

</section>

<style>
.game-back {
    padding: 30px 0 25px;
    margin-bottom: 30px;
    text-align: center;
    overflow: hidden;
    position: relative;
    min-height: 302px;
    box-shadow: 10px 10px 10px #d1d9e6, -10px -10px 10px #f7f7f7;
    border-radius: 12px;
}
.game-back .picture {
    display: inline-block;
    height: 130px;
    width: 130px;
    margin-bottom: 50px;
    z-index: 1;
    position: relative;
}
.game-back .picture::before {
    content: "";
    width: 100%;
    height: 0;
    border-radius: 50%;
    position: absolute;
    bottom: 135%;
    right: 0;
    left: 0;
    opacity: 0.9;
    transform: scale(3);
    transition: all 0.3s linear 0s;
}


.game-back:hover .picture::before {
    height: 100%;
}

.game-back .picture::after {
    content: "";
    width: 100%;
    height: 100%;
    border-radius: 50%;
    /* background-color: #1325d7; */
    position: absolute;
    top: 0;
    left: 0;
    z-index: -1;
}

.game-back .picture img {
    width: 100%;
    height: auto;
    /* border-radius: 50%; */
    transform: scale(1);
    transition: all 0.9s ease 0s;
}

.game-back:hover .picture img {
    
    /* background-color: #1325d7; */
    transform: scale(0.7);
}

.game-back .title {
    display: block;
    font-size: 15px;
    color: #7a7b7c;
    /* text-transform: capitalize; */
}

.game-back .social {
    width: 100%;
    padding: 0;
    margin: 0;
    background-color: #1325d7;
    position: absolute;
    bottom: -100px;
    left: 0;
    transition: all 0.5s ease 0s;
}

.game-back:hover .social {
    bottom: 0;
}

.game-back .social li {
    display: inline-block;
}

.game-back .social li a {
    display: block;
    padding: 10px;
    font-size: 17px;
    color: white;
    transition: all 0.3s ease 0s;
    text-decoration: none;
}

.game-back .social li a:hover {
    color: #1325d7;
    background-color: #f7f5ec;
}

</style>