<section>

<h3 class="title-morph">Accueil</h3>

<div class="stylebox" onclick="redirectPanel('panel.php?p=2')">
    <?php
    require "app/env.php";
    $premiereLettreName = substr($_SESSION['userNameLog'], 0, 1); ?>
    <div id="prePP" style="width: unset!important;">
        <?php if (!$_SESSION["userPpLog"]){ ?>
            <div id="PP" class="pp-morph" style="background-image: url('https://tyrolium.fr/generate-pp/?c=183153&l=<?= $premiereLettreName ?>')"></div>
        <?php } else { ?>
            <div id="PP" class="pp-morph" style="background-image: url('<?= $env_uploadUrl . "pp/" . $_SESSION["userPpLog"] ?>')"></div>
        <?php } ?>
    </div>
    <div>
        <h4>Votre profile</h4><br>
        <p>Username : <?= $_SESSION['userNameLog'] ?></p>
        <p>Mail : <?= $_SESSION['userEmailLog'] ?></p>
        <p>Nom d'affichage : <?php if(!empty($_SESSION['userDisNameLog']) ) { echo $_SESSION['userDisNameLog']; } else { echo '<i> Vide </i>'; } ?></p>
    </div>
</div>


    <h3 class="title-morph">Raccourci</h3>

<div class="flex-container">

        <div class="game-back" onclick="redirectPanel('panel.php?p=10')">
                <div class="picture">
                    <img class="img-fluid" src="https://tyrolium.fr/Contenu/Image/Tyrolium%20ServerMC%20Sword%203D.png">
                </div>

                <div class="team-content">
                    <h3 class="name">TyroServ</h3>
                </div>
        </div>
        <div class="game-back" onclick="redirectPanel('panel.php?p=8')">
            <div class="picture">
                <img class="img-fluid" src="assets/icone/game.png">
            </div>

            <div class="team-content secondtext">
                <h3 class="name">Vos jeux</h3>
                <small>5 jeux</small>
            </div>
        </div>

        <div class="game-back" onclick="redirectPanel('panel.php?p=7')">
            <div class="picture">
                <img class="img-fluid" src="assets/icone/service.png">
            </div>

            <div class="team-content secondtext">
                <h3 class="name">Vos Prestations</h3>
                <small>5 produits</small>
            </div>
        </div>

        <div class="game-back" onclick="redirectPanel('panel.php?p=9')">
            <div class="picture">
                <img class="img-fluid" src="assets/icone/server.png">
            </div>

            <div class="team-content secondtext">
                <h3 class="name">Vos Serveurs</h3>
                <small>5 produits</small>
            </div>
        </div>
</div>


    <h3 class="title-morph">Vos produits</h3>




</section>

<style>


.stylebox{

    margin-bottom: 30px;
    padding: 30px 0 25px 10px;
    /*box-shadow: 10px 10px 10px #d1d9e6, -10px -10px 10px #f7f7f7;*/
    border-radius: 12px;
    background: #EBECF0;
    box-shadow: -5px -5px 20px #FFF, 5px 5px 20px #BABECC;
    transition: all 0.2s ease 0s;
}


#PP {
    margin-left: 25px;
    margin-right: 25px;
}

.stylebox{
    display: flex;
}

@media (max-width: 710px) {
    #PP{
        margin: auto;
    }

    .stylebox{
        display: block;
    }

    #prePP{
        width: 100%;
    }

}

</style>
