<section id="panel-game">
    <h3 class="title-morph">Vos serveurs informatique</h3>
    <div class="flex-container">

            <div class="game-back" onclick="redirectPanel('https://solidserv.fr/')">
                <div class="picture">
                    <img class="img-fluid" src="assets/icone/add.png">
                </div>
                
                <div class="team-content">
                    <h3 class="name">Commandez</h3>
                    <h4 class="title">Serveur de SolidServ</h4>
                </div>
            </div>

            <div class="game-back" onclick="redirectPanel('panel.php?p=6')">
                <div class="picture">
                    <img class="img-fluid" src="assets/logo.png">
                </div>
                
                <div class="team-content">
                    <h3 class="name">Cloud User</h3>
                    <h4 class="title">Donnée du Compte Useritium</h4>
                </div>
            </div>

    </div>

</section>
