<section id="panel-game">
    <h3 class="title-morph">Vos prestations</h3>
    <div class="flex-container">

            <div class="game-back"  onclick="redirectPanel('https://tyrolium.fr/service.php')">
                <div class="picture">
                    <img class="img-fluid" src="assets/icone/add.png">
                </div>
                
                <div class="team-content">
                    <h3 class="name">Commandez</h3>
                    <h4 class="title">Prestations de Tyrolium</h4>
                </div>
            </div>

    </div>

</section>
