<section id="panel-tyroserv">

    <h2 class="title-morph">Profil TyroServ</h2>

    <?php

    require "app/env.php";
    $tyroservAccount = getTyroServ();

//    var_dump($tyroservAccount);

    if ($tyroservAccount){

    ?>

        <br><br>
        <div class="card-morph">
            <h3 style="font-size: 20px">Pseudo Minecraft :</h3><br>
            <h2 style="text-align: center"><?= $tyroservAccount['pseudo'] ?></h2>
        </div>

        <br><hr><br>

        <h3 class="title-morph">Skin Minecraft</h3>
        <div class="card-morph">

            <form method="POST" enctype="multipart/form-data">

                <div id="preSkin">
                    <?php if (!$tyroservAccount['skin']){ ?>
                        <div id="Skin" style="background-image: url('https://mineskin.eu/skin/<?= $tyroservAccount['pseudo'] ?>')"></div>
                    <?php } else { ?>
                        <div id="Skin" style="background-image: url('<?= $env_uploadUrl . "skin/" . $tyroservAccount['skin'] ?>')"></div>
                    <?php } ?>
                </div>

                <div class="form-group" style="margin-top: 25px">
                    <label>Votre Image (9 Mo Max)</label>
                    <input style="height: unset"  type="file" class="form-control" name="pictureSkinAdd">
                </div>

        <!--        <input type="checkbox" name="slim" value="">-->

                <input type="hidden" name="idEdit" value="<?= $_SESSION['userIdLog'] ?>">
                <br>
                <button type="submit" class="btn btn-morph btn-morph-primary"> <i class="icon ri-check-line"></i> Mettre à jour</button>

            </form>

        </div>


    <?php

    /* CAPE */

    $MyCape = [];
    $isSelected = 99999999;

    if (empty($tyroservAccount['cape'])) {
        $tyroservCape = "null";
    } else {
        $tyroservCape = $tyroservAccount['cape'];
    }

//    $json = file_get_contents('http://vps214.tyrolium.fr/api-cape/player.php?pseudo=' . $tyroservAccount['pseudo'] . '&idCapeUseritium='. $tyroservCape);
    $json = file_get_contents('http://127.0.0.1/Api-TyroModCape/player.php?pseudo=' . $tyroservAccount['pseudo'] . '&idCapeUseritium='. $tyroservCape);
//    $json2 = file_get_contents('http://vps214.tyrolium.fr/api-cape/wiki.php');
    $json2 = file_get_contents('http://127.0.0.1/Api-TyroModCape/wiki.php');
    $resultApiCape = json_decode($json);
    $resultAllCape = json_decode($json2);

    foreach ($resultAllCape as $oneCape) {

        foreach ($resultApiCape as $oneBuyCape) {

            if ($oneCape->id == $oneBuyCape->idCapes) {

                $temp = $oneBuyCape;
                $temp->cape = $oneCape;
                $MyCape[] = $temp;

                if ($temp->isSelected == 1) {
                    $isSelected = $temp->cape->id;
                }
            }

        }

    }

    ?>

        <br><hr><br>

        <h3 class="title-morph">Cape Minecraft</h3>

        <div class="card-morph">
                <button class="btn btn-morph" style="color: #212529"><i class="icon ri-shopping-bag-line"></i> Acheter une cape</button><br><br>

                <form method="POST" enctype="multipart/form-data">
                    <div class="card-group" style=" align-items: center;">

                        <div data-id="vide" class="cardcape <?php if ($isSelected == 99999999) echo "active" ?>">
                            <div class="cape canvas-container">
                                <canvas data-url="" class="pixelCanvas vide" width="100" height="160"></canvas>
                            </div>
                            <div class="cape-footer">
                                <input name="idCapeSelected" value="99999999" type="radio" <?php if ($isSelected == 99999999) echo "checked" ?>> Aucune Cape
                            </div>
                        </div>

                      <?php foreach ($MyCape as $oneCape) { ?>

                        <div data-id="<?= $oneCape->cape->id ?>" class="cardcape <?php if ($oneCape->isSelected) echo "active" ?>">
                            <div class="cape canvas-container">
                                <canvas data-url="http://vps214.tyrolium.fr/capes/capes/<?= $oneCape->cape->url ?>" class="pixelCanvas" width="100" height="160"></canvas>
                            </div>
                            <div class="cape-footer">
                                <input name="idCapeSelected" value="<?= $oneCape->cape->id ?>" type="radio" <?php if ($oneCape->isSelected) echo "checked" ?>> <?= $oneCape->cape->name ?>
                            </div>
                        </div>

                      <?php } ?>
                    </div>

                    <input type="hidden" name="idCapeOld" value="<?= $isSelected ?>">
                    <input type="hidden" name="idEdit" value="<?= $_SESSION['userIdLog'] ?>">

                    <br>
                    <button id="capeUpdate" disabled class="btn btn-morph btn-morph-primary" type="submit"><i class="icon ri-check-line"></i> Appliqué la cape</button>
                </form>

            <?php } else { ?>

                    <div class="card-morph">

                    <h4>Vous n'avez jamais joué à Tyroserv</h4><br>
                    <a class="btn-morph btn-morph-primary" style="text-align: center" href="https://tyroserv.fr" target="_blank">Go TyroServ.fr</a>

                    </div>

            <?php } ?>

        </div>

</section>

<style>

    /* SKIN */

    #Skin {
        width: 200px;
        height: 200px;
        box-shadow: 0px 4px 83px rgba(0, 0, 0, 0.24);
        background-size: contain;
        background-color: #919191;
        background-repeat: no-repeat;
        margin: auto;

        image-rendering: -moz-crisp-edges;
        image-rendering: -o-crisp-edges;
        image-rendering: -webkit-optimize-contrast;
        image-rendering: crisp-edges;
        -ms-interpolation-mode: nearest-neighbor;
    }

    #preSkin{
        width: 100%;
    }

    /* CAPE */

    .card-group{
        justify-content: center;
    }

    .cardcape.active{
        border: 2px solid #007bff !important;
    }

    .cape-footer{
        text-align: center;
        color: #5a5a5a;

        margin-right: 15px;
        margin-bottom: 15px;
        margin-left: 15px;

    }

    .cardcape{
        /*border: 1px solid rgba(0,0,0,.125);*/
        border: 2px solid #aba09c !important;
        /*border-radius: .25rem;*/
        margin: 10px;
        width: 206px;
        height: 269px;
    }

    .cape{
        margin-top: 30px;
        margin-right: auto;
        margin-bottom: 15px;
        margin-left: auto;

        width: 100px;
        height: 160px;

        background-size: 639px;
        background-position-y: 7%;
        background-position-x: -10px;

        image-rendering: -moz-crisp-edges;
        image-rendering: -o-crisp-edges;
        image-rendering: -webkit-optimize-contrast;
        image-rendering: crisp-edges;
        -ms-interpolation-mode: nearest-neighbor;

    }

    .canvas-container {
        width: 100px;
        height: 160px;
    }
    canvas {
        width: 100%;
        height: 100%;
        image-rendering: pixelated;
    }

    canvas.vide{
        border: 2px dashed #aba09c;
    }

    button#capeUpdate:disabled{
        opacity: 0.50;
        color: black;
    }

    @media (max-width: 992px) {
        .layout .content {
            padding: 19px 10px;
        }
    }



</style>

<script>


    var currentCapeId = <?= $isSelected ?>;
    var chooseCapeId;

    /* CHANGEMENT DE COULEUR A LA SELECTION DE LA CAPE */
    window.addEventListener('DOMContentLoaded', function() {

        let cardCapes = document.querySelectorAll('.cardcape');

        cardCapes.forEach(function(cardCape) {

            cardCape.addEventListener('click', function() {
                cardCapes.forEach(function(otherCardCape) {
                    otherCardCape.classList.remove('active');

                    let radioButton = otherCardCape.querySelector('input[type="radio"]');
                    if (radioButton) {
                        radioButton.checked = false;
                    }
                });

                this.classList.add('active');

                let radioButton = this.querySelector('input[type="radio"]');
                if (radioButton) {
                    radioButton.checked = true;
                }
            });
        });
    });

    /* ACTIVATION DU BTN UPLOAD CAPE */
    window.addEventListener('DOMContentLoaded', function() {
        var submitButton = document.getElementById('capeUpdate');
        var cardCapes = document.querySelectorAll('.cardcape');

        cardCapes.forEach(function(cardCape) {
            if (cardCape.classList.contains('active')) {
                currentCapeId = cardCape.getAttribute('data-id');
            }
            cardCape.addEventListener('click', function() {
                var thisCapeId = this.getAttribute('data-id');
                chooseCapeId = thisCapeId;
                if (thisCapeId != currentCapeId) {
                    submitButton.disabled = false;
                } else {
                    submitButton.disabled = true;
                }
            });
        });
    });

    /* AFFICHAGE DES CAPES */
    window.onload = function() {

        var canvases = document.querySelectorAll('.pixelCanvas');

        canvases.forEach(function(canvas) {

            var context = canvas.getContext('2d');
            var image = new Image();
            var imageUrl = canvas.getAttribute('data-url');
            image.src = imageUrl;

            image.onload = function () {
                context.imageSmoothingEnabled = false;

                var sourceX = 1;
                var sourceY = 1;
                var sourceWidth = 10;
                var sourceHeight = 16;
                var destX = 0;
                var destY = 0;
                var destWidth = canvas.width;
                var destHeight = canvas.height;

                context.drawImage(image, sourceX, sourceY, sourceWidth, sourceHeight, destX, destY, destWidth, destHeight);

            };
        })
    };

    function updateSkin() {
        window.location.href = '?p=10&cape=' + chooseCapeId + '&idEdit=' + <?= $tyroservAccount['idTyroServ'] ?> ;
    }


</script>

